module.exports = {
  main: [ { source: { id: 'google-news', name: 'Google News' },
    author: 'Jacqueline Howard and Kevin Liptak, CNN',
    title: 'Trump in \'very good health overall\' but obese, according to physical exam results',
    description: 'President Donald Trump, 72, is in "very good health overall," according to results from his physical examination, which were released on Thursday.',
    url: 'https://www.cnn.com/2019/02/14/health/trump-physical-results-2019-bn/index.html',
    urlToImage: 'https://cdn.cnn.com/cnnnext/dam/assets/190207155623-04-trump-health-trump-walking-super-tease.jpg',
    publishedAt: '2019-02-14T22:07:00+00:00',
    content: '(CNN)President Donald Trump, 72, isin "very good health overall,"according to results from his physical examination, which were released on Thursday. \r\nTrump underwent a physical examination at the Walter Reed military hospital on Friday, performed and superv… [+3807 chars]' },
  { source: { id: 'google-news', name: 'Google News' },
    author: '',
    title: 'McCabe\'s \'The Threat\' May Be Darkest Vision Of Trump Presidency Yet',
    description: 'Former FBI Deputy Director Andrew McCabe said Thursday that top Justice Dept. officials discussed invoking the 25th Amendment. But his new book is about far more than that.',
    url: 'https://www.npr.org/2019/02/14/694670497/mccabes-the-threat-may-be-darkest-vision-of-trump-presidency-yet',
    urlToImage: 'https://media.npr.org/assets/img/2019/02/14/gettyimages-699428310_wide-fb33f45b12afaeea1fdc349228fa3e62715fcb34.jpg?s=1400',
    publishedAt: '2019-02-14T22:03:00+00:00',
    content: 'Andrew McCabe, the former acting director of the FBI, says President Trump\'s treatment of the bureau and its probe of Russian interference in the 2016 presidential campaign was so disturbing during the spring of 2017 that Justice Department officials discusse… [+8304 chars]' },
  { source: { id: 'google-news', name: 'Google News' },
    author: 'https://www.washingtonexaminer.com/author/tiana-lowe',
    title: 'This is not a national emergency: Congress must update the National Emergency Act',
    description: 'The threat of illegal immigration mirrors that of climate change: Both must be dealt with at some point, but neither issue is immediate.',
    url: 'https://www.washingtonexaminer.com/opinion/this-is-not-a-national-emergency-congress-must-update-the-national-emergency-act',
    urlToImage: 'https://mediadc.brightspotcdn.com/dims4/default/cc93d6e/2147483647/strip/true/crop/4200x2205+0+110/resize/1200x630!/quality/90/?url=https%3A%2F%2Fmediadc.brightspotcdn.com%2F2a%2F40%2Fae753db54a87811078d13818b07d%2Fap-19043725239569.jpg',
    publishedAt: '2019-02-14T21:50:00+00:00',
    content: 'Senate Majority Leader Mitch McConnell, R-Ky., has decided to embrace his inner Harry Reid and greenlight President Trump\'s emergency declaration. \r\nAs John Yoo noted earlier this month, the courts may find that Trump is within his rights to mobilize the mili… [+2771 chars]' },
  { source: { id: 'google-news', name: 'Google News' },
    author: 'Jen Kirby',
    title: 'Brexit news: Theresa May loses yet another Brexit vote',
    description: 'The hardline Brexiteers in her party have said they don’t like her approach, undercutting her (already weak) position with the European Union.',
    url: 'https://www.vox.com/world/2019/2/14/18225098/brexit-theresa-may-parliament-vote-negotiations',
    urlToImage: 'https://cdn.vox-cdn.com/thumbor/yaewiJxaFOLtYKa8ljoMHj3TTP0=/0x0:5472x2865/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/13759480/1094820900.jpg.jpg',
    publishedAt: '2019-02-14T21:50:00+00:00',
    content: 'British Prime Minister Theresa May asked Parliament earlier this week to give her a little more time to renegotiate part of her unpopular Brexit deal with the European Union.\r\nParliament just responded with a resounding nope, voting down the motion 303 to 258… [+4093 chars]' },
  { source: { id: 'google-news', name: 'Google News' },
    author: 'J.D. Capelouto, Vanessa McCray',
    title: 'Candy sends 28 middle school students to hospitals; GBI handling testing',
    description: 'More than two dozen students were sent to hospitals on Valentine’s Day after ingesting snacks...',
    url: 'https://www.ajc.com/news/breaking-news/breaking-candy-sends-middle-school-students-hospitals/97v5TDErsebYzDEnVG2zTP/',
    urlToImage: 'https://www.myajc.com/rf/image_large/Pub/p10/AJC/2019/02/14/Images/stretcher.JPG',
    publishedAt: '2019-02-14T21:43:54+00:00',
    content: 'More than two dozen students were sent to hospitals on Valentine’s Day after ingesting snacks and candy at a south Fulton County middle school Thursday.\r\nThe Sandtown Middle School students were taken to Children’s Healthcare of Atlanta campuses at Hughes Spa… [+1926 chars]' },
  { source: { id: 'google-news', name: 'Google News' },
    author: 'Associated Press',
    title: 'Israel\'s Netanyahu denies agreeing to Holocaust distortion',
    description: 'Israeli Prime Minister Benjamin Netanyahu has denied suggestions of going along with Holocaust historical revisionism in Poland.',
    url: 'https://www.foxnews.com/world/israels-netanyahu-denies-agreeing-to-holocaust-distortion',
    urlToImage: 'https://static.foxnews.com/foxnews.com/content/uploads/2019/02/ContentBroker_contentid-ec00afebeadd4848b51115f9311ce123.png',
    publishedAt: '2019-02-14T21:27:10+00:00',
    content: null },
  { source: { id: 'google-news', name: 'Google News' },
    author: 'Jon Schuppe',
    title: 'William Barr was confirmed as U.S. attorney general. Here\'s what to expect on crime, immigration and marijuana.',
    description: 'William Barr, who previously served as attorney general under the first President Bush, has embraced hard-line positions on immigration and crime.',
    url: 'https://www.nbcnews.com/news/us-news/william-barr-was-confirmed-u-s-attorney-general-here-s-n971066',
    urlToImage: 'https://media4.s-nbcnews.com/j/newscms/2019_07/2752716/190213-william-barr-ew-645p_1e4e42551eab7e4825e2ee21780a4383.nbcnews-fp-1200-630.jpg',
    publishedAt: '2019-02-14T20:00:00+00:00',
    content: 'Get breaking news alerts and special reports. The news and stories that matter, delivered weekday mornings.\r\nSUBSCRIBE\r\nFeb. 14, 2019, 8:00 PM GMT\r\nThe Senate voted Thursday to approve William Barr as the next attorney general and successor to Jeff Sessions, … [+6023 chars]' },
  { source: { id: 'google-news', name: 'Google News' },
    author: null,
    title: '9 LSU frat members arrested in connection with DKE closure',
    description: 'Nine members of LSU\'s Delta Kappa Epsilon fraternity have been arrested and accused of hazing and other related offenses',
    url: 'https://katc.com/news/covering-louisiana/2019/02/14/nine-lsu-frat-members-arrested-in-connection-with-dke-closure/',
    urlToImage: 'https://s3.amazonaws.com/cordillera-network/wp-content/uploads/sites/3/2019/02/14152405/5c65d0422c315.image-1.jpg',
    publishedAt: '2019-02-14T16:46:27+00:00',
    content: null },
  { source: { id: 'google-news', name: 'Google News' },
    author: '',
    title: 'Federal Watchdog Issues Scathing Report On Ed Department\'s Handling Of Student Loans',
    description: 'The department\'s own inspector general says student loan companies aren\'t following the rules, and that the government isn\'t doing enough to hold them accountable.',
    url: 'https://www.npr.org/2019/02/14/694477547/federal-watchdog-issues-scathing-report-on-ed-departments-handling-of-student-lo',
    urlToImage: 'https://media.npr.org/assets/img/2019/02/14/hbarczyk_npr_studentloan_final_wide-2188af857eed6f0bdd1f464faeaad6334fc653d3.jpeg?s=1400',
    publishedAt: '2019-02-14T16:20:00+00:00',
    content: 'Updated at 3:13 p.m. ET\r\nA critical new report from the U.S. Department of Education\'s Office of Inspector General finds the department\'s student loan unit failed to adequately supervise the companies it pays to manage the nation\'s trillion-dollar portfolio o… [+6252 chars]' },
  { source: { id: 'google-news', name: 'Google News' },
    author: 'German Lopez',
    title: 'Parkland shooting anniversary: America’s gun problem, explained in 5 facts',
    description: 'America can prevent shootings. But it has to come to grips with the problem.',
    url: 'https://www.vox.com/policy-and-politics/2018/2/21/17028930/gun-violence-mass-shootings-us-statistics-charts',
    urlToImage: 'https://cdn.vox-cdn.com/thumbor/pjCy4oEHi1mmIXxnD-HdtcAqo6g=/0x0:5568x2915/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/10262379/GettyImages_858367878.jpg',
    publishedAt: '2019-02-14T15:42:00+00:00',
    content: 'A year ago today, on February 14, 2018, a gunman walked into Marjory Stoneman Douglas High School in Parkland, Florida, killed 17 people, and wounded 17 others. The shooting inspired a wave of activism, leading to the March for Our Lives in Washington, DC, an… [+17628 chars]' } ],
  other: [ { source: { id: 'usa-today', name: 'USA Today' },
    author: null,
    title: 'Police: DKE frat members arrested for hazing, urinating upon LSU pledges',
    description: 'Nine members of DKE fraternity, under suspension at Louisiana State University, were arrested Thursday on charges related to a hazing incident.',
    url: 'https://www.usatoday.com/story/news/nation/2019/02/14/9-lsu-fraternity-members-arrested-hazing-charges/2872824002/?utm_source=google&utm_medium=amp&utm_campaign=speakable',
    urlToImage: 'https://www.gannett-cdn.com/presto/2019/02/14/USAT/09325324-3111-48ab-96bd-9a93bd76be44-DUCKWORTH_CADE_1700100234_250063.jpg?crop=1042,593,x0,y288&width=3200&height=1680&fit=bounds',
    publishedAt: '2019-02-15T01:47:14+00:00',
    content: 'Nine members of a fraternity under suspension at Louisiana State University were arrested Thursday on charges related to hazing pledges who were urinated on, forced to lay on broken glass, and ordered to stand for hours in painful positions, according to auth… [+5855 chars]' },
  { source: { id: 'usa-today', name: 'USA Today' },
    author: null,
    title: 'Donald Trump\'s weight up, cholesterol down, president\'s doctor discloses after physical exam',
    description: 'President Trump – who once described his exercise regimen as "I walk, I this, I that" – has long faced questions about his health.',
    url: 'https://www.usatoday.com/story/news/politics/2019/02/14/donald-trump-weighs-243-pounds-doctor-says-after-physical/2846158002/?utm_source=google&utm_medium=amp&utm_campaign=speakable',
    urlToImage: 'https://www.gannett-cdn.com/presto/2019/02/12/USAT/66dfc269-de13-4163-b16a-b28c9f0ab526-AFP_AFP_1DC2E5.JPG?crop=4211,2358,x0,y364&width=3200&height=1680&fit=bounds',
    publishedAt: '2019-02-15T01:45:43+00:00',
    content: 'President Donald Trump on Air Force One\r\n (Photo11: NICHOLAS KAMM, AFP/Getty Images)\r\nWASHINGTON  President Donald Trump weighed in at 243 pounds during his physical last week, an increase of four pounds from last year that makes him technically obese, accord… [+3454 chars]' },
  { source: { id: 'cnn', name: 'CNN' },
    author: 'Alex Rogers and Ted Barrett, CNN',
    title: 'Republicans warn Trump against decision to declare emergency to build border wall',
    description: 'President Donald Trump will sign a bill to avert another government shutdown, but also issue a national emergency declaration to build a wall on the US southern border, according to Senate Majority Leader Mitch McConnell, replacing lawmakers\' most pressing pr…',
    url: 'http://us.cnn.com/2019/02/14/politics/congress-republicans-national-emergency/index.html',
    urlToImage: 'https://cdn.cnn.com/cnnnext/dam/assets/180912131037-susan-collins-07-25-2018-super-tease.jpg',
    publishedAt: '2019-02-15T01:44:17Z',
    content: '(CNN)President Donald Trump will sign a bill to avert another government shutdown, but also issue a national emergency declaration to build a wall on the US southern border, according to Senate Majority Leader Mitch McConnell, replacing lawmakers\' most pressi… [+5174 chars]' },
  { source: { id: 'usa-today', name: 'USA Today' },
    author: null,
    title: 'Runner attacked by mountain lion wrestled with it before killing it by stepping on its neck',
    description: 'Travis Kauffman was running on the trails near Fort Collins when the mountain lion lunged at him and locked onto his wrist with its jaws.',
    url: 'https://www.coloradoan.com/story/news/2019/02/14/watch-live-meet-colorado-man-who-killed-mountain-lion-self-defense/2868484002?utm_source=google&utm_medium=amp&utm_campaign=speakable',
    urlToImage: 'https://www.gannett-cdn.com/presto/2019/02/14/PFTC/bbf5e8ef-8bc7-46ea-a572-0b95abcbaee7--CougarMan-008-FTC0214.JPG?crop=3599,2016,x0,y143&width=3200&height=1680&fit=bounds',
    publishedAt: '2019-02-15T01:43:09+00:00',
    content: 'Travis Kauffman was able to fight off a mountain lion after the animal attacked him on a trail near Fort Collins.\r\n Colorado Parks and Wildlife, Fort Collins Coloradoan\r\nFORT COLLINS, Colo. Travis Kauffman was 6 miles into an uphill run through ice-covered tr… [+6911 chars]' },
  { source: { id: 'usa-today', name: 'USA Today' },
    author: null,
    title: 'El Niño finally forms, what does this mean for our weather?',
    description: 'During an El Niño, water temperatures in the central and eastern tropical Pacific Ocean get a few degrees warmer than average for an extended time.',
    url: 'https://www.usatoday.com/story/news/nation/2019/02/14/el-nino-natural-warming-ocean-water-forms-climate-scientists/2868209002/?utm_source=google&utm_medium=amp&utm_campaign=speakable',
    urlToImage: 'https://www.gannett-cdn.com/-mm-/af70c934437c4ec9e3e296804b8e926ae70e5ae0/c=0-251-4925-3033/local/-/media/2017/01/30/USATODAY/USATODAY/636214045427487771-AFP-548290131.jpg?width=3200&height=1680&fit=crop',
    publishedAt: '2019-02-15T01:41:52+00:00',
    content: 'Despite their simple names, these weather systems can cause a whole lot of trouble.\r\n USA TODAY\r\nAfter months of indications that it was coming, infamous climate agitator El Niño formed this week, climate scientists announced Thursday. \r\n"Weak El Niño conditi… [+3038 chars]' },
  { source: { id: 'usa-today', name: 'USA Today' },
    author: null,
    title: 'Trump attacked Obama for using executive powers on immigration, now plans to do the same thing',
    description: 'Although the positions were reversed, Obama was also frustrated by a lack of congressional action for what he viewed as a broken immigration system.',
    url: 'https://www.usatoday.com/story/news/politics/2019/02/14/donald-trump-2014-president-shouldnt-use-executive-authority/2875541002/?utm_source=google&utm_medium=amp&utm_campaign=speakable',
    urlToImage: 'https://www.gannett-cdn.com/presto/2019/02/14/USAT/76c86aba-5ca1-46f5-b803-86aceefdc569-GTY_1124726388_1.JPG?crop=5183,2902,x0,y0&width=3200&height=1680&fit=bounds',
    publishedAt: '2019-02-15T01:41:04+00:00',
    content: 'After a bipartisan vote on border security legislation, senators appeared split over President Donald Trump\'s plan to declare a national emergency, allowing him to build more of his border wall. (Feb. 14)\r\n AP\r\nWASHINGTON  There\'s always a tweet. \r\nIn 2014, P… [+3736 chars]' },
  { source: { id: 'usa-today', name: 'USA Today' },
    author: null,
    title: 'Trump\'s emergency declaration would trigger a drawn-out legal fight',
    description: 'President Donald Trump plans to declare a national emergency to speed construction of his proposed wall on the U.S.-Mexican border.',
    url: 'https://www.usatoday.com/story/news/politics/2019/02/14/donald-trump-emergency-border-wall-long-legal-fight/2548526002/?utm_source=google&utm_medium=amp&utm_campaign=speakable',
    urlToImage: 'https://www.gannett-cdn.com/presto/2019/01/10/USAT/e981b5cc-9e93-4271-93f2-4d50d82aeb70-3385.jpg?crop=4409,2480,x1,y202&width=3200&height=1680&fit=bounds',
    publishedAt: '2019-02-15T01:40:04+00:00',
    content: 'Senate Majority Leader Mitch McConnell says President Donald Trump has indicated he\'s prepared to sign the government funding bill to avert another government shutdown and issue a national emergency on the border at the same time. (Feb. 14)\r\n AP\r\nWASHINGTON  … [+6195 chars]' },
  { source: { id: 'associated-press', name: 'Associated Press' },
    author: 'ALAN FRAM, CATHERINE LUCEY and ANDREW TAYLOR',
    title: 'Senate OKs border deal; Trump will sign, declare emergency',
    description: 'WASHINGTON (AP) — Congress steamed toward lopsided approval of a border security compromise Thursday that would avert a second painful government shutdown, but a new confrontation was ignited — this time over President Donald Trump\'s plan to bypass lawmakers …',
    url: 'https://apnews.com/34dde5f8a2404e039d6fe819136e92f5',
    urlToImage: '',
    publishedAt: '2019-02-15T01:39:35Z',
    content: null },
  { source: { id: 'fox-news', name: 'Fox News' },
    author: 'Fox News',
    title: 'Reports of Jussie Smollett\'s alleged attack being a hoax \'unconfirmed by case detectives,\' Chicago police say',
    description: 'Chicago police said Thursday evening that reports about the alleged attack on "Empire" actor Jussie Smollett being a hoax were "unconfirmed by case detectives."',
    url: 'https://www.foxnews.com/entertainment/reports-of-jussie-smolletts-alleged-attack-being-a-hoax-unconfirmed-by-case-detectives-chicago-police-say',
    urlToImage: 'https://media2.foxnews.com/BrightCove/694940094001/2019/02/12/694940094001_6001364600001_6001362460001-vs.jpg',
    publishedAt: '2019-02-15T01:38:04.3542116Z',
    content: 'Chicago police said Thursday evening that reports about the alleged attack on "Empire" actor Jussie Smollett being a hoax were "unconfirmed by case detectives."\r\nAnthony Guglielmi, the chief communications officer for the Chicago Police Department (CPD), twee… [+1701 chars]' },
  { source: { id: 'axios', name: 'Axios' },
    author: 'Alison Snyder',
    title: 'Axios Science',
    description: 'Smart and timely news and analysis of scientific breakthroughs, by Andrew Freedman. Thursday mornings',
    url: 'https://www.axios.com/newsletters/axios-science-c0d01a53-cf42-4d75-bb61-d09dfb3cbd1b.html',
    urlToImage: 'https://images.axios.com/-39Hd8CUbzXgh8iQOnoJFk3jAjI=/1920x1080/smart/social/science3.jpg',
    publishedAt: '2019-02-15T01:38:00.8073375Z',
    content: 'The federal government may try to take action if states don\'t tighten their vaccine exemption laws and measles continues to spread in sections of the U.S., FDA Commissioner Scott Gottlieb tells Axios\' Eileen Drage O\'Reilly. \r\nBackground: States are allowed to… [+1644 chars]' },
  { source: { id: 'axios', name: 'Axios' },
    author: 'Alison Snyder',
    title: 'Disruptive ideas largely stem from two contrasting approaches, research shows',
    description: 'Each addresses a common enemy of innovation: how we interfere with each other\'s thinking and creativity.',
    url: 'https://www.axios.com/science-where-disruptive-ideas-come-from-caf796cd-7f68-4106-b415-0cabcdcbbd4f.html',
    urlToImage: 'https://images.axios.com/MaIeb4flf4XkFlhKbaN4xaFLfj8=/0x0:1920x1080/1920x1080/2019/02/15/1550194221542.gif',
    publishedAt: '2019-02-15T01:36:36.502Z',
    content: 'Big idea 1: Small teams of scientists are more likely than large ones to produce disruptive ideas, according to a new analysis of more than 65 million scientific papers, patents and computer code published between 1954 and 2014.\r\nA study was deemed more disru… [+2512 chars]' },
  { source: { id: 'time', name: 'Time' },
    author: 'Abby Vesoulis',
    title: 'President Donald Trump Is Now One of 93 Million Obese Americans',
    description: 'The results of President Trump\'s annual physical were released Thursday and show his weight gain qualifies him as technically obese.',
    url: 'http://time.com/5530149/trump-2019-physician-report-obese/',
    urlToImage: 'https://timedotcom.files.wordpress.com/2019/02/trump-2019-physician-report-fast-food.jpg?quality=85',
    publishedAt: '2019-02-15T01:34:07Z',
    content: 'Approximately 93.3 million Americans are considered to be obese, according to Centers for Disease Control and Prevention estimates. Now, President Donald Trump is among them.\r\nDr. Sean P. Conley, the President’s physician, released the results of Trump’s annu… [+3191 chars]' },
  { source: { id: 'axios', name: 'Axios' },
    author: 'Axios',
    title: 'Elizabeth Warren: Everything you need to know about the 2020 candidate',
    description: 'She has voted with Trump 13.5% of the time.',
    url: 'https://www.axios.com/elizabeth-warren-2020-presidential-election-factsheet-9570cc43-0eee-4efd-be82-b3f498632a60.html',
    urlToImage: 'https://images.axios.com/gfADriH4pzu92bKvd4OX4jpBiDI=/0x386:6720x4166/1920x1080/2019/02/13/1550081181547.jpg',
    publishedAt: '2019-02-15T01:30:00Z',
    content: 'Democrat Elizabeth Warren is a Massachusetts senator known for her consumer advocacy and efforts to weaken big financial institutions. Her brainchild, the Consumer Financial Protection Bureau, was created in 2011.\r\nCurrent position: Senator from Massachusetts… [+1525 chars]' },
  { source: { id: 'cnn', name: 'CNN' },
    author: 'Andrew Kaczynski, CNN',
    title: 'Trump once called executive action on immigration dangerous, unconstitutional and impeachable',
    description: 'President Donald Trump once said taking executive action on immigration was an unconstitutional action that could lead to impeachment.',
    url: 'http://us.cnn.com/2019/02/14/politics/kfile-trump-immigration-executive-action-2014/index.html',
    urlToImage: 'https://cdn.cnn.com/cnnnext/dam/assets/190214105544-donald-trump-0213-super-tease.jpg',
    publishedAt: '2019-02-15T01:27:53Z',
    content: null },
  { source: { id: 'associated-press', name: 'Associated Press' },
    author: 'BERNARD CONDON',
    title: 'Trump Org scraps plans for 2 hotel chains, blaming politics',
    description: 'NEW YORK (AP) — President Donald Trump\'s company is scrapping plans for two new hotel chains announced two years ago, casting blame in part on a hostile political environment.The Trump Organization said Thursday that it will no longer try to open hotels under…',
    url: 'https://apnews.com/d9267665dc75434d8cbb1059b1ec5bef',
    urlToImage: 'https://storage.googleapis.com/afs-prod/media/media:1e530fd3e30a43bd84dbe00359d0b442/3000.jpeg',
    publishedAt: '2019-02-15T01:26:09Z',
    content: null },
  { source: { id: 'reuters', name: 'Reuters' },
    author: 'Zachary Fagenson',
    title: '\'Forever haunted\' Parkland mourns a year after shooting',
    description: 'One year after the Valentine\'s Day massacre inside a Florida school, students and families leading a nationwide push for school and gun safety paused on Thursday to mark the anniversary of the deadliest U.S. high school shooting.',
    url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/1Wux7T4En8c/forever-haunted-parkland-mourns-a-year-after-shooting-idUSKCN1Q31IZ',
    urlToImage: 'https://s1.reutersmedia.net/resources/r/?m=02&d=20190214&t=2&i=1356676223&w=1200&r=LYNXNPEF1D1Z0',
    publishedAt: '2019-02-15T01:25:55Z',
    content: 'PARKLAND, Fla. (Reuters) - One year after the Valentine’s Day massacre inside a Florida school, students and families leading a nationwide push for school and gun safety paused on Thursday to mark the anniversary of the deadliest U.S. high school shooting. \r\n… [+3538 chars]' },
  { source: { id: 'cnn', name: 'CNN' },
    author: null,
    title: 'Rep. Ilhan Omar deals with fallout from tweets - CNN Video',
    description: 'Freshman Congresswoman Ilhan Omar (D-MN) has received fallout from both sides of the aisle over a series of tweets widely perceived as anti-Semitic. CNN\'s Manu Raju reports.',
    url: 'http://us.cnn.com/videos/politics/2019/02/14/omar-tweets-controversy-fallout-trump-manu-raju-ebof-dnt-vpx.cnn',
    urlToImage: 'https://cdn.cnn.com/cnnnext/dam/assets/190213103514-ilhan-omar-super-tease.jpg',
    publishedAt: '2019-02-15T01:23:29.1919852Z',
    content: 'Chat with us in Facebook Messenger. Find out what\'s happening in the world as it unfolds.' },
  { source: { id: 'fox-news', name: 'Fox News' },
    author: 'Fox News',
    title: 'Man says killing mountain lion with bare hands \'was just like a wrestling match\'',
    description: 'The man who was attacked by a mountain lion during a run in Colorado earlier this month explained how he suffocated the young cat — and survived with minimal injuries.',
    url: 'https://www.foxnews.com/us/man-says-killing-mountain-lion-with-bare-hands-was-just-like-a-wrestling-match',
    urlToImage: 'https://media2.foxnews.com/BrightCove/694940094001/2019/02/05/694940094001_5998870848001_5998868856001-vs.jpg',
    publishedAt: '2019-02-15T01:23:14.8482472Z',
    content: 'The man who was attacked by a mountain lion during a run in Colorado earlier this month explained how he suffocated the young cat — and survived with minimal injuries.\r\nTravis Kauffman spoke publicly for the first time on Thursday after the incident, which to… [+2848 chars]' },
  { source: { id: 'fox-news', name: 'Fox News' },
    author: 'Fox News',
    title: 'Doug Schoen: Amazon’s cancellation of move to NYC is catastrophic and could hurt far-left Dems at polls',
    description: 'Amazon’s announcement Thursday that it is abandoning plans to construct a second corporate headquarters New York City is bad news for the city, New York state and the metropolitan region.',
    url: 'https://www.foxnews.com/opinion/doug-schoen-amazons-cancellation-of-a-move-to-nyc-is-bad-news-and-could-hurt-far-left-dems-at-polls',
    urlToImage: 'https://media2.foxnews.com/BrightCove/694940094001/2019/02/14/694940094001_6002282335001_6002287921001-vs.jpg',
    publishedAt: '2019-02-15T01:23:09.160766Z',
    content: 'Amazon’s announcement Thursday that it is abandoning plans to construct a second corporate headquarters New York City is a catastrophic loss for the city, New York state and the metropolitan region.\r\nAs a New Yorker, I find it immensely disappointing to see t… [+5074 chars]' },
  { source: { id: 'the-huffington-post', name: 'The Huffington Post' },
    author: 'Mary Papenfuss',
    title: 'People Call Out Trump’s Hypocrisy On National Emergency With His Own Anti-Obama Tweet',
    description: 'Trump once slammed the previous president for taking executive action because he was "unable to negotiate w/ Congress."',
    url: 'https://www.huffpost.com/entry/trump-obama-tweet-national-emergency_n_5c65f3e8e4b033a79940c986',
    urlToImage: 'https://img.huffingtonpost.com/asset/5c65fa5723000076012298cf.jpeg?cache=jklq7hbc1e&ops=1910_1000',
    publishedAt: '2019-02-15T01:21:19Z',
    content: 'The Twitter blowback over President Donald Trumps plan to declare a national emergency to build his border wall has zeroed in on Trumps own past tweet bashing then-President Barack Obama for subverting the Constitution with an executive action because he was … [+3583 chars]' },
  { source: { id: 'the-huffington-post', name: 'The Huffington Post' },
    author: 'Rebecca Shapiro',
    title: 'Michigan Gov. Gretchen Whitmer Calls Out \'Garbage\' Fox Article About Her Body',
    description: 'A local Fox television station claimed it was defending the governor against sexist attacks online.',
    url: 'https://www.huffpost.com/entry/gretchen-whitmer-michigan-governor-fox-article-body_n_5c65e8d0e4b01757c369a7e8',
    urlToImage: 'https://img.huffingtonpost.com/asset/5c65ec8a3b00007b046b7ce5.jpeg?cache=jaxauc9hhf&ops=1910_1000',
    publishedAt: '2019-02-15T01:16:54Z',
    content: 'Michigan Gov. Gretchen Whitmer responded on Thursday to a story produced by a local Fox news station that highlighted sexist comments about her appearance, calling the piece way out of line.\r\nAfter Whitmers first State of the State address on Tuesday, Fox 2 N… [+2873 chars]' },
  { source: { id: 'associated-press', name: 'Associated Press' },
    author: 'IAN PHILLIPS and JOSHUA GOODMAN',
    title: 'AP Interview: Maduro reveals secret meetings with US envoy',
    description: 'CARACAS, Venezuela (AP) — President Nicolas Maduro has invited a U.S. special envoy to Venezuela after revealing in an AP interview on Thursday that his foreign minister recently held secret talks with the U.S. official in New York.A senior Venezuelan officia…',
    url: 'https://apnews.com/ee79b8c8f3a8497eab4a54741612dec8',
    urlToImage: 'https://storage.googleapis.com/afs-prod/media/media:5ed7b2d7426140f893e9943f6e453c8f/3000.jpeg',
    publishedAt: '2019-02-15T01:14:44Z',
    content: null },
  { source: { id: 'reuters', name: 'Reuters' },
    author: 'Hideyuki Sano',
    title: 'Asian stocks slip after grim U.S. retail sales data',
    description: 'Asian stocks slipped on Friday after grim U.S. retail sales figures raised fresh doubts about the strength of the U.S. economy, offsetting optimism on trade talks between the United States and China.',
    url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/YiPHbqdFCvM/asian-stocks-slip-after-grim-u-s-retail-sales-data-idUSKCN1Q4043',
    urlToImage: 'https://s3.reutersmedia.net/resources/r/?m=02&d=20190215&t=2&i=1356700659&w=1200&r=LYNXNPEF1E025',
    publishedAt: '2019-02-15T01:14:05Z',
    content: 'TOKYO (Reuters) - Asian stocks slipped on Friday after grim U.S. retail sales figures raised fresh doubts about the strength of the U.S. economy, offsetting optimism on trade talks between the United States and China. \r\nAlso casting a shadow, the White House … [+3400 chars]' },
  { source: { id: 'reuters', name: 'Reuters' },
    author: 'Corina Pons',
    title: 'Venezuela\'s Maduro ramps up legal fight against Guaido\'s challenge',
    description: 'Venezuelan President Nicolas Maduro\'s government stepped up a legal battle against efforts to oust him on Thursday, while the opposition said the international community had pledged more than $100 million in humanitarian aid for the country.',
    url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/7K-ZlEF3I04/venezuelas-maduro-ramps-up-legal-fight-against-guaidos-challenge-idUSKCN1Q325K',
    urlToImage: 'https://s2.reutersmedia.net/resources/r/?m=02&d=20190215&t=2&i=1356700424&w=1200&r=LYNXNPEF1D193',
    publishedAt: '2019-02-15T01:12:06Z',
    content: 'CARACAS/WASHINGTON (Reuters) - Venezuelan President Nicolas Maduro’s government stepped up a legal battle against efforts to oust him on Thursday, while the opposition said the international community had pledged more than $100 million in humanitarian aid for… [+4690 chars]' },
  { source: { id: 'reuters', name: 'Reuters' },
    author: 'Reuters Editorial',
    title: 'House advances border security funds toward final passage',
    description: 'The U.S. House of Representatives on Thursday approved the rules for debating a bill to avert another partial federal government shutdown by funding several agencies but denying President Donald Trump\'s demand for $5.7 billion to build a wall on the U.S.-Mexi…',
    url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/PHO0KSftjew/house-advances-border-security-funds-toward-final-passage-idUSKCN1Q403Z',
    urlToImage: 'https://s4.reutersmedia.net/resources_v2/images/rcom-default.png',
    publishedAt: '2019-02-15T01:09:23Z',
    content: 'WASHINGTON (Reuters) - The U.S. House of Representatives on Thursday approved the rules for debating a bill to avert another partial federal government shutdown by funding several agencies but denying President Donald Trump’s demand for $5.7 billion to build … [+327 chars]' },
  { source: { id: 'fox-news', name: 'Fox News' },
    author: 'Fox News',
    title: 'Senate Judiciary Committee wants McCabe to testify',
    description: 'Republican Senate Judiciary Committee Chairman Graham did not rule out a subpoena to compel testimony from Deputy Attorney General Rod Rosenstein and former Deputy FBI Director Andrew McCabe; chief intelligence correspondent Catherine Herridge reports.',
    url: 'https://video.foxnews.com/v/6002380114001/',
    urlToImage: 'https://a57.foxnews.com/media2.foxnews.com/BrightCove/694940094001/2019/02/14/640/360/694940094001_6002379734001_6002380114001-vs.jpg',
    publishedAt: '2019-02-15T01:08:05.0344706Z',
    content: null },
  { source: { id: 'fox-news', name: 'Fox News' },
    author: 'Fox News',
    title: 'Secretary Pompeo on containing the threat from Iran, negotiating with North Korea and the Trump doctrine',
    description: 'Secretary of State Mike Pompeo discusses foreign policy challenges with Bret Baier, anchor of \'Special Report.\'',
    url: 'https://video.foxnews.com/v/6002381656001/',
    urlToImage: 'https://a57.foxnews.com/media2.foxnews.com/BrightCove/694940094001/2019/02/14/640/360/694940094001_6002384578001_6002381656001-vs.jpg',
    publishedAt: '2019-02-15T01:07:52.2387863Z',
    content: null },
  { source: { id: 'cbs-news', name: 'CBS News' },
    author: null,
    title: 'Amazon pulls out of plan for New York headquarters',
    description: 'On Thursday, retail giant Amazon abruptly canceled plans to build a second headquarters in New York City. The company has facing fierce backlash from local leaders and activists. David Begnaud reports.',
    url: 'https://www.cbsnews.com/video/amazon-pulls-out-of-plan-for-new-york-headquarters/',
    urlToImage: 'https://cbsnews2.cbsistatic.com/hub/i/r/2019/02/14/ee1430fd-2c14-43a7-aba1-653f538b4f6e/thumbnail/1200x630/dfb406ab9308817055801c2b9434dd35/0214-en-amazon-begnaud-1783364-640x360.jpg',
    publishedAt: '2019-02-15T01:02:38+00:00',
    content: null },
  { source: { id: 'associated-press', name: 'Associated Press' },
    author: 'JOSEPH PISANI and ALEXANDRA OLSON',
    title: 'Amazon dumps NYC headquarters and its promised 25,000 jobs',
    description: 'NEW YORK (AP) — Amazon abruptly dropped plans Thursday for a big new headquarters in New York that would have brought 25,000 jobs to the city, reversing course after politicians and activists objected to the nearly $3 billion in incentives promised to what is…',
    url: 'https://apnews.com/d736c681d54c4b6c846602917fad76db',
    urlToImage: 'https://storage.googleapis.com/afs-prod/media/media:4384d00f98794efda4fe66e974f9bd33/3000.jpeg',
    publishedAt: '2019-02-15T01:01:01Z',
    content: null },
  { source: { id: 'reuters', name: 'Reuters' },
    author: 'Keith Coffman',
    title: 'Colorado man who strangled mountain lion describes life-or-death struggle',
    description: 'A 31-year-old man who fended off and suffocated a mountain lion when it attacked him on a Colorado jogging trail last week described on Thursday how he killed the big cat by stepping on its throat during a life-and-death struggle.',
    url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/WGDuOyFBl-g/colorado-man-who-strangled-mountain-lion-describes-life-or-death-struggle-idUSKCN1Q402Q',
    urlToImage: 'https://s2.reutersmedia.net/resources/r/?m=02&d=20190215&t=2&i=1356696612&w=1200&r=LYNXNPEF1E013',
    publishedAt: '2019-02-15T00:56:15Z',
    content: 'DENVER (Reuters) - A 31-year-old man who fended off and suffocated a mountain lion when it attacked him on a Colorado jogging trail last week described on Thursday how he killed the big cat by stepping on its throat during a life-and-death struggle. \r\nSpeakin… [+2150 chars]' },
  { source: { id: 'axios', name: 'Axios' },
    author: 'David McCabe',
    title: 'Report: FTC talking to Facebook about huge fine',
    description: 'The penalty is said to be in the billions of dollars.',
    url: 'https://www.axios.com/report-facebook-talking-to-ftc-about-huge-fine-1550189355-1ac2cd86-1d8b-4619-913f-0bd2f6ef81a5.html',
    urlToImage: 'https://images.axios.com/aThciuVsMD4uj2goOq4d4V-Ff8A=/0x158:3871x2335/1920x1080/2019/02/15/1550191820154.jpg',
    publishedAt: '2019-02-15T00:55:14.956Z',
    content: 'Facebook is negotiating with the Federal Trade Commission over a possible multi-billion dollar fine to settle an investigation into privacy violations by the firm, the Washington Post reported Thursday.\r\nWhy it matters: Previous FTC privacy fines levied again… [+208 chars]' },
  { source: { id: 'reuters', name: 'Reuters' },
    author: 'Reuters Editorial',
    title: 'Pompeo: U.S. aims to \'get as far down the road as we can\' with North Korea',
    description: 'The United States aims to "get as far down the road as we can" ahead of a summit with North Korea in Vietnam this month, U.S. Secretary of State Mike Pompeo said on Thursday.',
    url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/W4PskHJfZiQ/pompeo-u-s-aims-to-get-as-far-down-the-road-as-we-can-with-north-korea-idUSKCN1Q32AF',
    urlToImage: 'https://s3.reutersmedia.net/resources/r/?m=02&d=20190215&t=2&i=1356694220&w=1200&r=LYNXNPEF1D1DQ',
    publishedAt: '2019-02-15T00:51:36Z',
    content: 'WARSAW (Reuters) - The United States aims to “get as far down the road as we can” ahead of a summit with North Korea in Vietnam this month, U.S. Secretary of State Mike Pompeo said on Thursday. \r\nPompeo said he was sending his team back to Asia in the coming … [+2410 chars]' },
  { source: { id: 'axios', name: 'Axios' },
    author: 'Erica Pandey',
    title: 'What New Yorkers have to say about Amazon pulling the plug',
    description: 'Amazon\'s decision is not entirely surprising',
    url: 'https://www.axios.com/amazon-hq2-new-york-city-residents-65b005cd-6f19-4ff4-8bfb-e1e4f0d45fd8.html',
    urlToImage: 'https://images.axios.com/H554Bhl-EjhOYucz3SlW38ZqjQg=/0x470:5538x3585/1920x1080/2019/02/15/1550190701151.jpg',
    publishedAt: '2019-02-15T00:42:06.022Z',
    content: 'What\'s happening: Amazon said it will add jobs to 17 of its existing offices around the country rather than build in New York, angry at pushback that spilled over here and elsewhere in the city over the $3 billion price tag promised to attract the company, as… [+1700 chars]' },
  { source: { id: 'cnn-es', name: 'CNN Spanish' },
    author: 'CNN',
    title: 'Trump firmará la ley de financiamiento y declarará una emergencia nacional, dice McConnell',
    description: 'El jueves el Senado de EE.UU. aprobó el proyecto para financiar el Gobierno y ahora pasará a la Cámara de Representantes. Si se aprueba allí, la medida se enviará a la Casa Blanca.',
    url: 'https://cnnespanol.cnn.com/2019/02/14/trump-firmara-la-ley-de-financiamiento-y-declarara-una-emergencia-nacional-dice-mcconnell/',
    urlToImage: 'https://cnnespanol2.files.wordpress.com/2019/02/190131125124-01-trump-oval-office-0131-super-169.jpg?quality=100&strip=info',
    publishedAt: '2019-02-15T00:41:18Z',
    content: '(CNN) — El presidente de EE.UU. Donald Trump planea firmar una ley de seguridad fronteriza y declarará una emergencia nacional para asegurar los fondos financiamiento de un muro fronterizo, terminando por ahora un enfrentamiento con el Congreso por su promesa… [+679 chars]' },
  { source: { id: 'associated-press', name: 'Associated Press' },
    author: 'ANITA SNOW',
    title: 'Deadly blue \'Mexican oxy\' pills take toll on US Southwest',
    description: 'TUCSON, Ariz. (AP) — Aaron Francisco Chavez swallowed at least one of the sky blue pills at a Halloween party before falling asleep forever. He became yet another victim killed by a flood of illicit fentanyl smuggled from Mexico by the Sinaloa cartel into the…',
    url: 'https://apnews.com/d2296529ea94472d9f0d010f7bb99a2d',
    urlToImage: 'https://storage.googleapis.com/afs-prod/media/media:71bbcc9b18d24915b0a43cd46efc39a7/3000.jpeg',
    publishedAt: '2019-02-15T00:37:52Z',
    content: null },
  { source: { id: 'cbs-news', name: 'CBS News' },
    author: null,
    title: 'Trump slams Andrew McCabe after "60 Minutes" interview',
    description: 'President Trump was quick to react to a "60 Minutes" interview with Andrew McCabe, the former deputy director of the FBI. McCabe told Scott Pelley why he was concerned in a meeting with the president. Paula Reid reports.',
    url: 'https://www.cbsnews.com/video/trump-slams-andrew-mccabe-after-60-minutes-interview/',
    urlToImage: 'https://cbsnews1.cbsistatic.com/hub/i/r/2019/02/14/9371b292-56c9-44a8-8ffb-f74db1a6e299/thumbnail/1200x630/18716a84a12dafbbccb0bf54c409f919/0214-en-mccabereaction-reid-1783344-640x360.jpg',
    publishedAt: '2019-02-15T00:27:56+00:00',
    content: null },
  { source: { id: 'axios', name: 'Axios' },
    author: 'Steve LeVine',
    title: 'Axios Future',
    description: 'Innovations in automation, mobility, society, cities, genetics, blockchain and more, by Steve LeVine. Weekday evenings',
    url: 'https://www.axios.com/newsletters/axios-future-7989266c-97d5-4437-ad55-f378eb0f1cea.html',
    urlToImage: 'https://images.axios.com/_0qpnn8IFtoPaOiflacynkS6MZo=/1920x1080/smart/social/future3.jpg',
    publishedAt: '2019-02-15T00:22:55.9303737Z',
    content: 'LONG ISLAND CITY, New York On the corner of 41st Avenue and 12th Street, right in front of the Queens Library Tech Lab, people were giddy, furious and astonished at the news they heard today: Amazon, after all, will not build a gigantic new headquarters in th… [+2290 chars]' },
  { source: { id: 'reuters', name: 'Reuters' },
    author: 'Andrew Hay',
    title: 'Monster mudslides, water rescues as storm punishes California',
    description: 'Motorists swam for their lives and residents were rescued from homes sliding downhill as the wettest winter storm of the year triggered floods and mudslides across California on Thursday.',
    url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/AsHOzGG2o3w/monster-mudslides-water-rescues-as-storm-punishes-california-idUSKCN1Q317L',
    urlToImage: 'https://s3.reutersmedia.net/resources/r/?m=02&d=20190215&t=2&i=1356689182&w=1200&r=LYNXNPEF1E00J',
    publishedAt: '2019-02-15T00:22:37Z',
    content: '(Reuters) - Motorists swam for their lives and residents were rescued from homes sliding downhill as the wettest winter storm of the year triggered floods and mudslides across California on Thursday. \r\nIn Sausalito, just across the Golden Gate Bridge from San… [+2564 chars]' },
  { source: { id: 'associated-press', name: 'Associated Press' },
    author: 'TERENCE CHEA and JOHN ANTCZAK',
    title: 'Mudslide sweeps house off hill as storm pounds California',
    description: 'SAUSALITO, Calif. (AP) — Waves of heavy rain pounded California on Thursday, washing away a mountain highway, triggering a mudslide that destroyed homes, and forcing residents to flee communities scorched by wildfires last year.The powerful system swept in fr…',
    url: 'https://apnews.com/86acb18aa1d44ca6a5213e4a37f9887b',
    urlToImage: 'https://storage.googleapis.com/afs-prod/media/media:db9fd1575be14fa4ae3b434d4ba5abd1/2430.jpeg',
    publishedAt: '2019-02-15T00:19:24Z',
    content: null },
  { source: { id: 'cbs-news', name: 'CBS News' },
    author: null,
    title: '"Juliet Club" responds to love letters sent to Verona',
    description: 'As the setting for "Romeo and Juliet," Verona, Italy is undeniably romantic. So people from all over send love letters to Verona, and a group of volunteers make sure to respond. Seth Doane explains.',
    url: 'https://www.cbsnews.com/video/juliet-club-responds-to-love-letters-sent-to-verona/',
    urlToImage: 'https://cbsnews3.cbsistatic.com/hub/i/r/2019/02/15/732befe4-0c67-49d1-a33a-cc40c7713b47/thumbnail/1200x630/f97b382510f6edb704d92d3d4c714484/0214-en-veronaletters-doane-1783404-640x360.jpg',
    publishedAt: '2019-02-15T00:17:38+00:00',
    content: null },
  { source: { id: 'usa-today', name: 'USA Today' },
    author: null,
    title: 'National emergency plan announced via iPhone Notes app? Twitter noticed',
    description: 'Notes, known for its textured background and sans serif font, has long been used for celebrity apologies and shopping lists.',
    url: 'https://www.usatoday.com/story/news/politics/2019/02/14/trump-national-emergency-via-iphone-notes-app-twitter-noticed/2875667002/?utm_source=google&utm_medium=amp&utm_campaign=speakable',
    urlToImage: 'https://www.gannett-cdn.com/presto/2019/02/14/USAT/a43c6793-6a33-47be-82f5-31916104dc6a-AP_Trump_2.JPG?crop=3438,1934,x0,y0&width=3200&height=1680&fit=bounds',
    publishedAt: '2019-02-15T00:14:46+00:00',
    content: 'House Speaker Nancy Pelosi rallied against the possibility of President Donald Trump declaring a national emergency. She says Republicans should have some dismay to the door that they are opening."\r\n USA TODAY\r\nPresident Donald Trump plans to declare a nation… [+2015 chars]' },
  { source: { id: 'reuters', name: 'Reuters' },
    author: 'Manjul Paul',
    title: 'Chance of a U.S. recession up, number of Fed rate hikes down: Reuters poll',
    description: 'There is a one-in-four chance of a U.S. recession in the next 12 months, a scenario that should keep the Federal Reserve from raising interest rates next month, according to a Reuters poll of economists who now expect only one rate hike this year.',
    url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/r1gDRYmaRus/chance-of-a-u-s-recession-up-number-of-fed-rate-hikes-down-reuters-poll-idUSKCN1Q400K',
    urlToImage: 'https://s4.reutersmedia.net/resources/r/?m=02&d=20190215&t=2&i=1356686109&w=1200&r=LYNXNPEF1E009',
    publishedAt: '2019-02-15T00:10:32Z',
    content: 'BENGALURU (Reuters) - There is a one-in-four chance of a U.S. recession in the next 12 months, a scenario that should keep the Federal Reserve from raising interest rates next month, according to a Reuters poll of economists who now expect only one rate hike … [+3867 chars]' },
  { source: { id: 'cbs-news', name: 'CBS News' },
    author: null,
    title: 'Colorado man recalls surviving mountain lion attack',
    description: 'While on a run earlier this month, Travis Kauffman said he came face-to-face with a mountain lion. His fear turned into a primal struggle to survive. Mireya Villarreal reports.',
    url: 'https://www.cbsnews.com/video/colorado-man-recalls-surviving-mountain-lion-attack/',
    urlToImage: 'https://cbsnews2.cbsistatic.com/hub/i/r/2019/02/15/9c2e817e-64ea-4e92-9d32-76501a28d707/thumbnail/1200x630/45d6e99dc224d1b6569e9e73f9bb4881/0214-en-mountainlion-villarreal-1783394-640x360.jpg',
    publishedAt: '2019-02-15T00:07:15+00:00',
    content: null },
  { source: { id: 'the-hill', name: 'The Hill' },
    author: 'Jordain Carney and Niv Elis',
    title: 'GOP braces for Trump\'s emergency declaration',
    description: 'The months-long battle over a proposed U.S.-Mexico border wall is set to escalate dramatically when President Trump declares a',
    url: 'http://thehill.com/homenews/senate/430121-gop-braces-for-trumps-emergency-declaration',
    urlToImage: 'https://thehill.com/sites/default/files/trumpdonald_021219getty.jpg',
    publishedAt: '2019-02-15T00:06:21Z',
    content: 'The months-long battle over a proposed U.S.-Mexico border wall is set to escalate dramatically when President TrumpDonald John TrumpLawmakers introduce bill to fund government, prevent shutdownTrump mulling 60-day delay for China tariff deadlineContractor bac… [+9802 chars]' },
  { source: { id: 'the-hill', name: 'The Hill' },
    author: 'Michael Burke',
    title: 'DOJ warns White House that national emergency will likely be blocked: report',
    description: 'The Department of Justice (DOJ) has warned the White House that the courts are likely to block a national emergency declaration to build a wall along the southern border, according to',
    url: 'http://thehill.com/homenews/administration/430122-doj-warns-white-house-that-national-emergency-will-likely-be-blocked',
    urlToImage: 'https://thehill.com/sites/default/files/trumpdonald_010219upi2_lead.jpg',
    publishedAt: '2019-02-15T00:05:35Z',
    content: 'The Department of Justice (DOJ) has warned the White House that the courts are likely to block a national emergency declaration to build a wall along the southern border, according to ABC News.\r\nThe White House, however, remains confident that it can win on a… [+1736 chars]' },
  { source: { id: 'cnn', name: 'CNN' },
    author: 'Katie Bernard, CNN',
    title: 'FCC: Nearly half the calls you receive this year will be spam',
    description: 'Nearly half the the calls made to US cell phones in 2019 will be spam according to a report from the Federal Communications Commission.  The report was on prevalence and prevention of illegal robocalls.',
    url: 'http://us.cnn.com/2019/02/14/politics/fcc-robocalls-report/index.html',
    urlToImage: 'https://cdn.cnn.com/cnnnext/dam/assets/181105160906-encuentro-llamada-telefonica-super-tease.jpg',
    publishedAt: '2019-02-15T00:04:02Z',
    content: null },
  { source: { id: 'cbs-news', name: 'CBS News' },
    author: null,
    title: 'Hackers exposing millions of patient medical records',
    description: 'The thefit of digitized medical records is on the rise. Hack attacks exposed more than 11 million patient records last year, up nearly 25 percent from 2017. Anna Werner reports.',
    url: 'https://www.cbsnews.com/video/hackers-exposing-millions-of-patient-medical-records/',
    urlToImage: 'https://cbsnews1.cbsistatic.com/hub/i/r/2019/02/15/a3120888-8057-4e5e-9833-66e4ac41fc6f/thumbnail/1200x630/2cb03a6e41d9c66b7235df6811afdc47/0214-en-medicalrecords-werner-1783383-640x360.jpg',
    publishedAt: '2019-02-15T00:02:37+00:00',
    content: null },
  { source: { id: 'cnn', name: 'CNN' },
    author: null,
    title: 'Government shutdown countdown: Live updates - CNNPolitics',
    description: 'The House will now debate the funding bill for an hour before moving on to the final vote.',
    url: 'https://www.cnn.com/politics/live-news/government-shutdown-february-2019/h_fe8e7f2b408e37910a4fae1c7834e9e5',
    urlToImage: 'https://cdn.cnn.com/cnnnext/dam/assets/190213080312-01-trump-cabinet-0212-super-tease.jpg',
    publishedAt: '2019-02-15T00:01:48Z',
    content: '(NICHOLAS KAMM/AFP/Getty Images)\r\nPresident Trump intends to declare a national emergency -- a move that could allow the administration to circumvent Congress and unlock money to build his signature border wall, the White House said today.   \r\nA national emer… [+1074 chars]' },
  { source: { id: 'axios', name: 'Axios' },
    author: 'Dave Lawler',
    title: 'Middle Eastern autocrats buoyed by Trump\'s backing',
    description: 'Egypt\'s Sisi is on course to rule for another decade or more.',
    url: 'https://www.axios.com/middle-east-trump-support-mbs-sisi-saudi-arabia-987732d4-c308-43a1-8eb0-48e60e351f3f.html',
    urlToImage: 'https://images.axios.com/OrQb8IYWc5qvKSwhcLyPDsICyBQ=/0x152:2000x1277/1920x1080/2019/02/14/1550185885413.jpg',
    publishedAt: '2019-02-15T00:00:00Z',
    content: 'Flashback: Sisi told CNBC before last year\'s sham election that he supported the system of "two four-year terms" and would "not interfere" with the constitution.\r\nBetween the lines: "Washingtons unquestioning embrace of Mr. el-Sisi, whom President Trump has c… [+980 chars]' },
  { source: { id: 'cbs-news', name: 'CBS News' },
    author: null,
    title: 'Parkland survivor Maddy Wilford describes the unseen wounds of trauma',
    description: 'One year ago, 14 students and three staff members were killed in Parkland, Florida. One of the most critically wounded survivors is Maddy Wilford, who has had to deal with the physical and emotional effects of the shooting. Mark Strassmann has her story.',
    url: 'https://www.cbsnews.com/video/parkland-survivor-maddy-wilford-describes-the-unseen-wounds-of-trauma/',
    urlToImage: 'https://cbsnews3.cbsistatic.com/hub/i/r/2019/02/14/43d33285-c92c-43cf-9195-eb6647a6fe40/thumbnail/1200x630/3c20955194f74acb7f22b8487862c674/0214-en-parklandanniversary-strassman-1783373-640x360.jpg',
    publishedAt: '2019-02-14T23:59:41+00:00',
    content: null }
  ]
}
